feat: support htmlwebpackplugin v4
DanielSchaffer/webpack-babel-multi-target-plugin pull request #55
Opened 2020-01-11 16:02 UTC by Austaras

fix #30

2020-01-12 04:09 UTC, erezvish commented
Oh wow, I see you got this already.
Thanks for making this fix!

2020-01-22 15:16 UTC, erezvish commented
@DanielSchaffer 
Who is supposed to review the changes, one of the current collaborators, you, or anyone interested?

2020-01-22 16:05 UTC, DanielSchaffer commented
@erezvish - hi, I’m sorry for the lack of communication! I’m in the process of switching jobs, so I’ve been scrambling to wrap things up and haven’t had time to look. I’ll try to set aside some time today to take a look so you guys can get unblocked.

2020-01-25 20:11 UTC, DanielSchaffer commented
@Austaras - my apologies for the delay - 

What you've got so far looks great, but I must also apologize that I also forgot that the `HtmlWebpackPlugin` hooks are also referenced in `NormalizeModuleIdsPlugin` - those will need to use the same logic you added to `BabelMultiTargetHtmlUpdater`. It might make sense to move the `isV4` `hook` logic into functions their own file.

I'd recommend try your changes out by using the examples - you can start the dev server by running this from the command line:

```
NODE_OPTIONS="--max-old-space-size=8192" yarn start
```

There are several examples, so the initial build may take a while to complete, especially on older machines - but once it's done, you can view the example projects by visiting http://localhost:3002/examples/angular/, and then following the links to each of the other examples. If all of the examples turn the background green after loading, you should be good to go.

Additionally, while I realize I haven't set up a formal "contributing guidelines", I'd much appreciate it if you could do the following:
- use `git rebase -i` to squash your commits into logical chunks - multiple commits are fine if they do unrelated things, but I'd prefer to avoid sequential commits that are something to the effect of "do the thing", and then "that didn't work, actually do the thing"
- please follow the guidelines established by [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) for your commit messages.

Thank you so much for your contributions on this, it is much appreciated!

2020-01-28 08:06 UTC, Austaras commented
Sorry for the dealy. Change as you requested. The Angular routing seems like broken in your branch too,  and other exmaple works fine

2020-01-31 14:04 UTC, Austaras commented
@DanielSchaffer would you take some time review my updated commit?

2020-01-31 17:03 UTC, DanielSchaffer commented
@Austaras I believe the broken Angular example is just due to using the wrong typescript version .. I'll fix that in another commit

2020-01-31 17:20 UTC, DanielSchaffer requested changes
The missing quotes on `undefined` is breaking it when used with `html-webpack-plugin@^3` - make sure you run the examples with both versions to ensure it works correctly. If you've got a `dist` directory from building the plugin previously, you may need to run `yarn build` after installing a different version so the change gets picked up.

2020-01-31 17:20 UTC, DanielSchaffer commented on src/html-webpack-plugin.polyfill.ts
> +const isV4 = typeof getHooks !== undefined
`undefined` needs to be quoted

```suggestion
const isV4 = typeof getHooks !== 'undefined'
```

2020-01-31 17:33 UTC, DanielSchaffer approved these changes

2020-01-31 17:33 UTC, merged

2020-01-31 18:03 UTC, DanielSchaffer commented
@Austaras @erezvish - this will be released as `2.5.0` (note: `2.4.0` is skipped due a some tagging/versioning snafu). Unfortunately, I'm having some issues with CI as Travis seems to have moved my cheese a bit - I can't poke at it right now, but I'll try and come back to it later this afternoon.

2020-01-31 19:45 UTC, erezvish commented
Thank you both for this, it is much appreciated!
I'll try the new version when released, no worries though if integration takes a little time.
Thank you again

2020-02-01 00:27 UTC, DanielSchaffer commented
@Austaras @erezvish pre-release: [`2.5.0-next.1`](https://www.npmjs.com/package/webpack-babel-multi-target-plugin/v/2.5.0-next.1)

2020-02-01 10:42 UTC, Austaras commented
@DanielSchaffer it mostly works fine, except for few minor problems
1. issue #56 
2. typing for babel-loader is not bundled so `fork-ts-checker` will compain about it
evrything else works fine

2020-02-02 08:44 UTC, erezvish commented
Hi, 
I can confirm that two builds are being created with Html webpack plugin (beta 8).
I'll need to work with it more to see if it's working properly.

Thanks for all the effort!

2020-02-02 17:32 UTC, DanielSchaffer commented
@Austaras can you write up an issue for this with repro steps?

> typing for babel-loader is not bundled so fork-ts-checker will complain about it