feat: add preset configuration to babel options
DanielSchaffer/webpack-babel-multi-target-plugin pull request #59
Opened 2020-02-12 13:42 UTC by semoal

resolves #54

2020-02-12 13:49 UTC, semoal commented
@DanielSchaffer ci is crashing but i'm not sure why, thanks in advance mate

2020-02-12 15:42 UTC, DanielSchaffer commented
Looks like I might need to disable code coverage on external branches? I might just disable it completely for now I haven’t written any unit tests 🤦‍♂️🙊

2020-02-12 16:59 UTC, DanielSchaffer commented
Looks like this is actually a somewhat common issue with coveralls. Go ahead and remove the the `- yarn coverage-report` line from `.travis.yml`. I'll figure a better solution out later.

2020-02-14 17:16 UTC, DanielSchaffer requested changes

2020-02-14 17:16 UTC, DanielSchaffer commented on src/babel-target.ts
> +        ...this.presets,
Have you checked this when `preset` is not set? Node generally doesn't like destructuring `undefined`

2020-02-14 17:16 UTC, DanielSchaffer commented on src/babel-target.ts
> +        ...this.presets,
Actually, looks like you set it to an empty array in the main plugin - in that case, it shouldn't be an optional param.

2020-02-19 22:12 UTC, semoal commented
@DanielSchaffer Fixed your proposal changes mate, once release i'll migrate my current webpack conf to yours, so probably i'll push more "fixes"

2020-03-10 16:18 UTC, DanielSchaffer approved these changes

2020-03-10 16:19 UTC, merged

2020-03-10 16:36 UTC, DanielSchaffer commented
Available in prerelease [v2.5.0-next.2](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/releases/tag/v2.5.0-next.2)

2020-03-10 16:40 UTC, barroudjo commented
awesome, thanks !